python train.py \
  -b 1 \
  -e 20 \
  -l 0.001 \
  -p 5 \
  -f 0.2 \
  -r 50 \
  -i 200 \
  -n 'test_varnet3' \
  -t '/content/drive/MyDrive/Data/train/' \
  -v '/content/drive/MyDrive/Data/val/' \
  --cascade 6 \
  --chans 12 \
  --sens_chans 5 \
  --input-key 'kspace' \
  --target-key 'image_label' \
  --max-key 'max' \
  --seed 430
